config/routes.rb
Cf::Application.routes.draw do

  resources :newsletters do
    member do
      post :mail_subscribers
    end
  end

  get 'tags/:tag', to: "blogs#index", as: :tag
  mount Ckeditor::Engine => '/ckeditor'

  resources :tips

  match "/search" => "home#search", :as => :search
  resources :magazines

  resources :videos

  resources :slides

  resources :right_ads

  resources :top_ads

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout" }, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :look_books do
    resources :photos
  end

  resources :functional_fashion_designers

  namespace :fashion do
    resources :fashion_juries
    resources :trend_spottings do
      resources :photos
    end
    resources :men_fashions  do
      resources :photos
    end
  end

  resources :trend_spottings do
    resources :photos
  end

  match '/fashion' => "fashion#show", :as => :fashion

  resource :runway

  namespace :runway do
    resources :collections do
      resources :photos
    end
    resources :seasons
    resources :years
  end

  namespace :style do
    resources :functional_fashions
    resources :look_books
    resources :tips
  end

  resources :redcarpets do
    resources :photos
  end

  resources :functional_fashions
  resources :blogs

  resources :features

  resources :photos
  resources :men_fashions do
    resources :photos
  end

  resources :fashion_juries

  resources :subscriptions

  match '/style' => "style#show", :as => :styles
  root :to => "home#index"

end

app/models/look_book.rb
class LookBook < ActiveRecord::Base
  attr_accessible :description, :name, :published_at
  has_many :photos, :as => :photoable
  validates :description, :name, :published_at, :presence => true

  scope :published, lambda { where('published_at <= ?', Time.now.utc) }
  scope :unpublished, lambda { where('published_at > ?', Time.now.utc) }
  scope :recent, order('published_at DESC')

  def previous
    self.class.where("id < ?", id).order("id desc").first
  end

  def next
    self.class.where("id > ?", id).order("id").first
  end

  def to_param
    "#{id} #{name}".parameterize
  end

  def last_published?
    self == self.class.published.last
  end

  def first_published?
    self == self.class.published.first
  end

  def published?
    published_at <= Time.zone.now
  end

end

app/controllers/look_books_controller.rb
class LookBooksController < ApplicationController
  load_and_authorize_resource
  def index
    @look_books = LookBook.accessible_by(current_ability).recent.page(params[:page]).per_page(27)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @look_books }
    end
  end

  # GET /look_books/1
  # GET /look_books/1.json
  def show
    @look_book = LookBook.find(params[:id])

    @photos = @look_book.photos
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @look_book }
    end
  end

  # GET /look_books/new
  # GET /look_books/new.json
  def new
    @look_book = LookBook.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @look_book }
    end
  end

  # GET /look_books/1/edit
  def edit
    @look_book = LookBook.find(params[:id])
  end

  # POST /look_books
  # POST /look_books.json
  def create
    @look_book = LookBook.new(params[:look_book])

    respond_to do |format|
      if @look_book.save
        format.html { redirect_to @look_book, notice: 'Look book was successfully created.' }
        format.json { render json: @look_book, status: :created, location: @look_book }
      else
        format.html { render action: "new", layout: "forms" }
        format.json { render json: @look_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /look_books/1
  # PUT /look_books/1.json
  def update
    @look_book = LookBook.find(params[:id])

    respond_to do |format|
      if @look_book.update_attributes(params[:look_book])
        format.html { redirect_to @look_book, notice: 'Look book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit", layout: "forms" }
        format.json { render json: @look_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /look_books/1
  # DELETE /look_books/1.json
  def destroy
    @look_book = LookBook.find(params[:id])
    @look_book.destroy

    respond_to do |format|
      format.html { redirect_to look_books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/style/look_books_controller.rb
class Style::LookBooksController < LookBooksController

end

app/helpers/look_books_helper.rb
module LookBooksHelper
end

app/helpers/style/look_books_helper.rb
module Style::LookBooksHelper
end

app/views/look_books/_form.html.erb
<%= simple_form_for(@look_book, html: {class: "form-horizontal"}) do |f| %>

  <%= f.input :name %>

  <%= f.input :description, as: :text, rows: 10, input_html: {style: "width: 757px"} %>

  <%= f.input :published_at, as: :string %>
  <div class="form-actions">
    <%= f.button :submit, class: "btn" %>
  </div>
<% end %>

app/views/look_books/_index_point.html.erb
<%= provide :title, "Look Book" %>
<section   class="span8">
  <header   class="heading">
    <h1><a    href="#">LOOK BOOK</a></h1>
  </header>
  <section  id="lookbook" class="stamp">

    <%= render :partial => "look_books/look_book", :collection => look_books %>

  </section>
  <% if look_books.next_page || look_books.previous_page %>
  <div class="pager" style="margin-top: 30px;">
    <%= will_paginate look_books %>
  </div>
  <% end %>

</section>

app/views/look_books/_look_book.html.erb
<%
 #locals
   look_book_photos = look_book.photos.limit(4)
%>

<div class="look_brand">
  <header style="padding-right: 10px;">
    <h2>
      <%= link_to look_book.name, style_look_book_path(look_book) %>
    </h2>
  </header>
  <ul  class="thmbs ">
    <% look_book_photos.each do |photo| %>
    <li class="span3">
      <a href="<%= image_path photo.photo(:original) %>" class="thumbnail transitionable" rel ="lightbox[roadtrip]<%= photo.photoable_id%>">
        <%= image_tag photo.photo(:trend_small), :style => "width:134px; height: 200px;" %>

      </a>
    </li>
    <% end %>
  </ul>
</div>

app/views/look_books/_look_book_photos.html.erb
<li class="item span4">
  <a href="<%= image_path photo.photo(:original) %>" class="thumbnail"  rel ="lightbox[roadtrip]<%= photo.photoable_id%>">
    <%= image_tag photo.photo(:trend_small), :alt => "", :class => "absolute-image" %>
  </a>
</li>

app/views/look_books/edit.html.erb
<section class="span12">
 <div class="page-header">
   <h1>Editing look book</h1>
 </div>

  <%= render 'form' %>

  <%= link_to 'Show', @look_book %> |
  <%= link_to 'Back', look_books_path %>
</section>

app/views/look_books/index.html.erb
<%= render "look_books/index_point", look_books: @look_books %>

app/views/look_books/new.html.erb
<section class="span12">
  <div class="page-header">
    <h1>Create a new look book</h1>
  </div>



  <%= render 'form' %>

  <%= link_to 'Back', look_books_path %>
</section>

app/views/look_books/show.html.erb
<section  id="redcarpet" class="stamp span8">
  <%= render "next_page", :obj => @look_book %>

  <header   class="show_header">
    <h1 class="">
      <%= @look_book.name %>
    </h1>
  </header>
  <div class="red_box row-fluid">
    <ul  class="thmbs row-fluid masonize">
      <%= render :partial => "look_books/look_book_photos", :collection => @photos, :as => :photo, :locals => {:redcarpet => @look_book} %>
    </ul>
  </div>
<% if can? :manage, @look_book %>
 <div class="form-actions">
   <%= link_to "Manage Photos", look_book_photos_path(@look_book), :class => "btn" %>
   <%= link_to "Edit", edit_look_book_path(@look_book), class: "btn" %>
   <%= link_to "Delete", @look_book, :method => :delete, data: {confirm: "Are you sure"}, class: "btn btn-danger" %>
 </div>
<% end %>

</section>

<%= content_for :javascript do %>
    <script type="text/javascript">
        var $redCarpet = $('.thmbs');
        $redCarpet.imagesLoaded(function(){
            $redCarpet.masonry({
                itemSelector : '.item',
                columnWidth : function( containerWidth ) {
                    return containerWidth / 3;
                }
            });
        });

    </script>

<% end %>