config/routes.rb
Cf::Application.routes.draw do

  resources :newsletters do
    member do
      post :mail_subscribers
    end
  end

  get 'tags/:tag', to: "blogs#index", as: :tag
  mount Ckeditor::Engine => '/ckeditor'

  resources :tips

  match "/search" => "home#search", :as => :search
  resources :magazines

  resources :videos

  resources :slides

  resources :right_ads

  resources :top_ads

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout" }, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :look_books do
    resources :photos
  end

  resources :functional_fashion_designers

  namespace :fashion do
    resources :fashion_juries
    resources :trend_spottings do
      resources :photos
    end
    resources :men_fashions  do
      resources :photos
    end
  end

  resources :trend_spottings do
    resources :photos
  end

  match '/fashion' => "fashion#show", :as => :fashion

  resource :runway

  namespace :runway do
    resources :collections do
      resources :photos
    end
    resources :seasons
    resources :years
  end

  namespace :style do
    resources :functional_fashions
    resources :look_books
    resources :tips
  end

  resources :redcarpets do
    resources :photos
  end

  resources :functional_fashions
  resources :blogs

  resources :features

  resources :photos
  resources :men_fashions do
    resources :photos
  end

  resources :fashion_juries

  resources :subscriptions

  match '/style' => "style#show", :as => :styles
  root :to => "home#index"

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  attr_accessible :body, :title
  validates :title, :body, :presence => true

  def summary
    self.body.gsub("&nbsp;", "")
  end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_admin_user
  def index
    @newsletters = Newsletter.page(params[:page]).per_page(27)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @newsletters }
    end
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
    @newsletter = Newsletter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @newsletter }
    end
  end

  # GET /newsletters/new
  # GET /newsletters/new.json
  def new
    @newsletter = Newsletter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @newsletter }
    end
  end

  # GET /newsletters/1/edit
  def edit
    @newsletter = Newsletter.find(params[:id])
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(params[:newsletter])

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully created.' }
        format.json { render json: @newsletter, status: :created, location: @newsletter }
      else
        format.html { render action: "new" }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /newsletters/1
  # PUT /newsletters/1.json
  def update
    @newsletter = Newsletter.find(params[:id])

    respond_to do |format|
      if @newsletter.update_attributes(params[:newsletter])
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter = Newsletter.find(params[:id])
    @newsletter.destroy

    respond_to do |format|
      format.html { redirect_to newsletters_url }
      format.json { head :no_content }
    end
  end

  def mail_subscribers
    @newsletter = Newsletter.find(params[:id])
    @subscriptions = Subscription.all
    @subscriptions.each do |subscription|
      NewsletterMailer.news(subscription.email, @newsletter).deliver
    end
    respond_to do |format|
      format.html { redirect_to newsletters_url, :notice => "sent news letter" }
      format.json { head :no_content }
    end
  end

  private

  def check_admin_user
    if ! current_user.admin
      redirect_to root_url
      flash[:alert] = "Not Authorised"
    end
  end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/newsletters/_form.html.erb
<%= simple_form_for(@newsletter, :html => {:class => "form-horizontal"}) do |f| %>
    <%= f.input :title, input_html: {class: "span9"} %>
    <%= f.input :body, :as => :ckeditor, :label => false, :input_html => { :toolbar => 'Full' } %>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/newsletters/_newsletter.html.erb
<div class="cover">
  <div class="caption heading_b" style="text-align: left;">
    <h2>
      <a href="<%= url_for newsletter %>" rel="tooltip" class="arrow_append" data-original-title="<%= newsletter.title %>">
        <%= newsletter.title %>
        <span class="arrow_r_after"></span>
      </a>
    </h2>
    <p><%= link_to sanitize(strip_tags(truncate(newsletter.summary, length: 180, :omission => ".. read more"))), newsletter_path(newsletter) %></p>
    <p class="blog_meta"> posted in
     <span class="date"> <%= newsletter.created_at.strftime("on %^b  %d  %I:%M%p")%></span>
     <%= link_to "send newsletter", mail_subscribers_newsletter_path(newsletter), :method => :post, class: "btn" %>
    </p>
  </div>
</div>

app/views/newsletters/edit.html.erb
<section   class="span12">
  <div class="page-header">
    <h1>Edit News Letter</h1>
  </div>


  <%= render 'form' %>

  <%= link_to 'Back', blogs_path %>
</section>

app/views/newsletters/index.html.erb
<%= provide :title, "News letter" %>
<section  id="redcarpet" class="stamp span8">
  <header   class="header_title">
    <h1><a    href="#">News Letters</a></h1>
  </header>
  <%= render @newsletters %>

  <div class="pager" style="margin-top: 30px;">
    <%= will_paginate @newsletters %>
  </div>



  <% if can? :manage, Newsletter %>
      <div class="form-actions">
        <%= link_to "Create Newsletter", new_newsletter_path, class: "btn" %>
      </div>
  <% end %>
</section>

app/views/newsletters/new.html.erb
<section   class="span12">
  <div class="page-header">
    <h1>Create Newsletter</h1>
  </div>


  <%= render 'form' %>

  <%= link_to 'Back', blogs_path %>
</section>

app/views/newsletters/show.html.erb
<%= provide :title, @newsletter.title %>
<section   class="trend_show span8">

  <header   class="show_header">
    <h1 class="">
      <%= @newsletter.title %>
    </h1>
  </header>
  <div   class="media">
    <%= raw @newsletter.body %>
  </div>

  <% if can? [:manage], @newsletter %>
      <div class="form-actions">
        <%= link_to 'Edit', edit_newsletter_path(@newsletter), class: "btn" %>
        <%= link_to 'Back', newsletters_path, class: "btn" %>
        <%= link_to "Delete", @newsletter, method: :delete, data: {confirm: "Are you sure"}, :class => "btn btn-danger" %>
      </div>
  <% end %>
</section>