config/routes.rb
Cf::Application.routes.draw do

  resources :newsletters do
    member do
      post :mail_subscribers
    end
  end

  get 'tags/:tag', to: "blogs#index", as: :tag
  mount Ckeditor::Engine => '/ckeditor'

  resources :tips

  match "/search" => "home#search", :as => :search
  resources :magazines

  resources :videos

  resources :slides

  resources :right_ads

  resources :top_ads

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout" }, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :look_books do
    resources :photos
  end

  resources :functional_fashion_designers

  namespace :fashion do
    resources :fashion_juries
    resources :trend_spottings do
      resources :photos
    end
    resources :men_fashions  do
      resources :photos
    end
  end

  resources :trend_spottings do
    resources :photos
  end

  match '/fashion' => "fashion#show", :as => :fashion

  resource :runway

  namespace :runway do
    resources :collections do
      resources :photos
    end
    resources :seasons
    resources :years
  end

  namespace :style do
    resources :functional_fashions
    resources :look_books
    resources :tips
  end

  resources :redcarpets do
    resources :photos
  end

  resources :functional_fashions
  resources :blogs

  resources :features

  resources :photos
  resources :men_fashions do
    resources :photos
  end

  resources :fashion_juries

  resources :subscriptions

  match '/style' => "style#show", :as => :styles
  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @blogs = Blog.published.recent.limit(4)
    @fashion_juries = FashionJury.published.recent.limit(3)
    @men_fashion = MenFashion.published.recent.first
    @functional_fashions = FunctionalFashion.published.recent.limit(2)
    @collections =  Runway::Collection.published.recent.limit(4)
    @trend_spotting = TrendSpotting.published.recent.includes(:photos).first
    @photos = @trend_spotting.photos.limit(6)  if @trend_spotting
    @videos = Video.published.recent.limit(7)
    @redcarpet = Redcarpet.published.recent.includes(:photos).first
    if @redcarpet
    @redcarpet_photos = @redcarpet.photos.limit(10)
    if @redcarpet_photos.size >= 10
      @rp = @redcarpet_photos.limit(10)
    else
      @rp = @redcarpet_photos.limit(8)
    end
    end
  end



  def search
    @q = params[:q]
    @blogs = Blog.published.where("title LIKE ?", "%#{@q}%")
    @fashion_juries = FashionJury.published.where("content LIKE ?", "%#{@q}%")
    @trend_spottings = TrendSpotting.published.where("title LIKE ?", "%#{@q}%" )
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_blog.html.erb
<section class="news">
  <header  >
    <h3>latest news...</h3>
  </header>
  <div	class="news_box">
 <% unless @blogs.empty? %>
    <div class="row-fluid ">
    <% first_blog = @blogs.first %>
      <div class="">
        <div class="span6">
          <%= link_to image_tag(first_blog.blog_image(:trend_small)), first_blog %>
        </div>
        <div class="span6">
          <div class="caption">
            <h4>
              <a href="<%= url_for first_blog %>" rel="tooltip" title="<%= first_blog.title %>" class="arrow_append">
                <%= first_blog.title %>
                <span class="arrow_r_after"></span>
              </a>
            </h4>
            <p><%= link_to sanitize(strip_tags(truncate(first_blog.summary, length: 180, :omission => ".. read more"))), first_blog %></p>
            <p class="date"><%= first_blog.published_at.strftime("%^b  %d  %I:%M%p")%></p>
          </div>
        </div>
      </div>
    </div>
<% end %>
    <div class="row-fluid ">

      <ul class="news-items items">
        <% @blogs.each do |blog| %>
            <% next if blog == @blogs.first %>
        <li>
          <div class="item">
            <div class="caption">
              <h4>
                <a href="<%= url_for blog %>" rel="tooltip" title="<%= blog.title %>" class="arrow_append">
                  <%= blog.title %>
                  <span class="arrow_r_after"></span>
                </a></h4>
              <p><%= link_to sanitize(strip_tags(truncate(blog.summary, length: 170, :omission => ".. read more"))), blog %></p>
              <p class="date"><%= link_to blog.published_at.strftime("%^b  %d  %I:%M%p"), blog %></p>
            </div>
          </div>
        </li>
         <% end %>
      </ul>
    </div>
    <div  class="more_box">
      <div  class="more">
        <span>more</span>
        <a href="<%= url_for blogs_path %>" class="more_link arrow_append">&nbsp;NEWS&nbsp;<span class="arrow_r_after"></span></a>
      </div>
    </div>
  </div>

</section>

app/views/home/_fashion.html.erb
<section  id="fashion" class="row-fluid">
  <div class="fashion_main">
    <header class="heading  caption heading_b">
      <h1>FASHION JURY</h1>
    </header>
    <div class="box">
      <ul class="fashion-items items">
        <% @fashion_juries.each do |fashion_jury| %>
        <li class="span4">
          <div class="polaroid">
            <%= link_to image_tag(fashion_jury.fashion_jury_image(:small), style: "width:140px; height: 208px;"), fashion_fashion_jury_path(fashion_jury, format: :js), :class => "imageLink", rel: "facebox" %>
            <div class="stats">
              <p><em class="s"></em><span class="saves"><%= fashion_jury.score %></span><em class="l">&nbsp;/&nbsp;</em><span class="likes">10</span> </p>
            </div>
            <div class="groups">
              <p class="small one_line">
                <%= fashion_jury.content %>
              </p>
              <%= link_to fashion_fashion_jury_path(fashion_jury, format: :js), :class => "comment_link block transitionable", rel: "facebox" do %>
                  <i class="icon-white icon-comment"></i>
                  <span class="comment_count"> Add </span>
                  comments
              <% end %>
            </div>
          </div>
        </li>
         <% end %>
      </ul>
      <div  class="more_box">

        <div  class="more">
          <span>more from</span>
          <a href="<%= url_for fashion_fashion_juries_path %>"   rel="tooltip" title="Style Diary" class="more_link arrow_append">&nbsp;FASHION JURY&nbsp;<span class="arrow_r_after"></span></a>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/_redcarpet.html.erb
<% @first_set = @rp[0.. 3] %>
<% @second_set = @rp[4..5] %>
<% @last_set = @rp[6..11] %>

<section id="red_carpet_moment" class="row-fluid">
  <div  class="heading    caption heading_b">
    <h1>RED CARPET MOMENTS</h1>
  </div>
  <div class="box ">
    <div class="row-fluid   col4">
      <% @first_set.each do |first| %>
      <div class="span3">
        <div class="thumbnail" >
          <a href="#" data-original-title="<%= first.caption %>" style="display: block;"><%= link_to image_tag(first.photo(:thumb)), @redcarpet %></a>
        </div>
      </div>
      <% end %>
    </div>
    <div class="divider"></div>
    <div class="row-fluid  col4_a">
      <div class="span3">
        <div class="thumbnail"  title="<%= @second_set.first.caption %>" >
          <a href="#" data-original-title="<%= @second_set.first.caption %>" style="display: block;"><%= link_to image_tag(@second_set.first.photo(:thumb)), @redcarpet %></a>
        </div>
      </div>
      <div class="span6">
        <div class="" >
          <div class="thumbnail">
            <div class="caption">
              <h1>
                <a href="<%= url_for @redcarpet %>"   rel="tooltip" title="<%= @redcarpet.title %>" class="arrow_append">
                  <%= @redcarpet.title %>
                  <span class="arrow_r_after"></span>
                </a></h1>
            </div>
          </div>
          <div  class="more_box">
            <div  class="more">
              <span>more from</span>
              <a href="<%= url_for redcarpets_path %>" class="more_link arrow_append">&nbsp;RED CARPET MOMENTS&nbsp;<span class="arrow_r_after"></span></a>
            </div>
          </div>
        </div>
      </div>
      <div class="span3">
        <div class="thumbnail">
          <a href="#" data-original-title="<%= @second_set.last.caption %>" style="display: block;"><%= link_to image_tag(@second_set.last.photo(:thumb)), @redcarpet %></a>
        </div>
      </div>
    </div>
    <div class="divider"></div>
    <div class="row-fluid   col4">
      <% @last_set.each do |last| %>
          <div class="span3">
            <div class="thumbnail" >
              <a href="#" data-original-title="<%= last.caption %>" style="display: block;"><%= link_to image_tag(last.photo(:thumb)), @redcarpet %></a>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</section>

app/views/home/_style.html.erb
<section  id="fashion_jury_main" class="row-fluid ">
  <header class="heading  caption heading_b">
    <h1>STYLE DIARY</h1>
  </header>

  <div class="box col2">
    <ul class="fashion-items items">
      <% @functional_fashions.each do |functional_fashion| %>
      <li class="span6   tile" >
        <div class="polaroid style transitionable">
          <div class="user_meta">
            <%= image_tag functional_fashion.functional_fashion_designer.icon(:trend_small), :class => "avatar", :alt => "" %>
            <div class="block">
              <%= link_to functional_fashion.functional_fashion_designer.name, functional_fashion.functional_fashion_designer, class: "name" %>
            </div>
          </div>
          <div class="divider"></div>

          <a href="<%= url_for style_functional_fashion_path(functional_fashion) %>" class="imageLink">
            <%= image_tag functional_fashion.functional_fashion_image(:trend_small) %>
          </a>
        </div>
      </li>
      <% end %>
    </ul>
    <div  class="more">
      <span>more from</span>
      <a href="<%= url_for style_functional_fashions_path %>"   rel="tooltip" title="style diary" class="more_link arrow_append">&nbsp;STYLE DIARY&nbsp;<span class="arrow_r_after"></span></a>
    </div>
  </div>
</section>

app/views/home/_trend.html.erb
<section id="trending_runway"  class="row-fluid">
  <div class="box col2">
    <% unless @collections.empty? %>
    <div class="span6">
      <div  class="heading  caption heading_b">
        <h1>RUNWAY</h1>
      </div>
      <% @collection = @collections.first %>
      <header   class="heading">
        <h1>
          <%= link_to @collection.name, @collection %>
        </h1>
      </header>
      <div class="trending_featured">
        <div class="trending_items tip_it_down"    rel="tooltip" title="<%= @collection.name %>">
          <%= image_tag @collection.collection_cover(:trend_small) %>
        </div>
      </div>


      <ul class="hot_items">
        <% @collections.each do |collection| %>
            <% next if collection == @collections.first %>
        <li>
          <a  href="<%= url_for collection %>"    class="arrow_append">
            <%= collection.name %>
            <span class="arrow_r_after"></span>
          </a>
        </li>
      <% end %>
      </ul>
      <div  class="more_box">
        <div  class="more">
          <span>more from</span>
          <a href="<%= url_for runway_path %>" class="more_link arrow_append">&nbsp;RUNWAY&nbsp;<span class="arrow_r_after"></span></a>
        </div>
      </div>
    </div>
    <% end %>
    <% if @trend_spotting %>
    <div class="span6">
      <div  class="heading    caption heading_b">
        <h1>TREND SPOTTING</h1>
      </div>
      <div class="trending_items">
        <div class="row-fluid">
          <header   class="heading">
            <h1>
              <%= link_to @trend_spotting.title, fashion_trend_spotting_path(@trend_spotting) %>
            </h1>
          </header>
        </div>
        <div class="item_grid">
          <ul  class="items row-fluid">
            <% @photos.each do |photo| %>
            <li	class="item span6">
              <div  class="thumbnail tip_it_down" rel="tooltip" title="<%= photo.caption %>">
                <%= link_to image_tag(photo.photo(:trend_small)), @trend_spotting %>
              </div>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div  class="more_box">
        <div  class="more">
          <span>more from</span>
          <a href="<%= url_for fashion_trend_spottings_path %>" class="more_link arrow_append">&nbsp;TREND SPOTTING&nbsp;<span class="arrow_r_after"></span></a>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</section>

app/views/home/_video.html.erb
<% unless @videos.empty? %>
<section id="video" class="row-fluid">
  <div class="span12  video_main">
    <div  class="heading    caption heading_b">
      <h1>CF VIDEOS</h1>
    </div>
    <div class="box col2">
      <div class="row-fluid ">
        <ul class="thumbnails span6 items row-fluid">
          <% @videos.each do |video| %>
          <% next if video == @videos.first %>
          <li  class="span6">
            <a href="<%= url_for video %>" class="thumbnail">
              <%= image_tag video.screen_shot(:thumb) %>
            </a>
          </li>
          <% end %>
        </ul>
        <div class="span6 ">
          <header    class="caption heading_b">
            <h2>
              VIDEO OF THE WEEK
            </h2>
          </header>
          <% @video = @videos.first %>
          <div>
            <a href="<%= url_for @video %>" class="thumbnail">
              <%= image_tag @video.screen_shot(:large) %>
            </a>
          </div>
          <header    class="caption heading_b">

            <h1>
              <a href="<%= url_for @video %>" rel="tooltip" class="arrow_append" data-original-title="<%= @video.title %>">
                <%= @video.title %>
                <span class="arrow_r_after"></span>
              </a>
            </h1>
          </header>
          <div  class="more">
            <span>more from</span>
            <a href="<%= url_for videos_path %>" class="more_link arrow_append">&nbsp;CF VIDEOS&nbsp;<span class="arrow_r_after"></span></a>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>
<% end %>

app/views/home/index.html.erb
<section  id="main_content" class="span8">
<section id="#featured" class="row-fluid  ">
  <div class="span12 featured_main">
    <div class="row-fluid col2  box">
      <div class="span6">

       <%= render "slide" %>
      </div>
      <div class="span6">
        <%= render "blog" unless @blogs.empty? %>
      </div>
    </div>
  </div>
</section>

<%= render "fashion" unless @fashion_juries.empty? %>
<%= render "style" unless @functional_fashions.empty? %>

<%= render "trend" %>

<%= render "video" %>

<% if @redcarpet %>
 <% if @redcarpet_photos.size >= 10 %>

    <%= render "redcarpet" %>

<% else %>

<section id="red_carpet_moment" class="row-fluid">
  <div  class="heading">
    <h1><%= link_to @redcarpet.title, @redcarpet %></h1>
  </div>
  <div class="box ">
    <% @rp.in_groups_of(4, false) do |row_cp| %>
    <div class="row-fluid   col4">
      <% row_cp.each do |cp| %>
      <div class="span3">
        <div class="thumbnail popdown" title="firstThis is The new complete fashion website" >
          <a class=""><%= link_to image_tag(cp.photo(:thumb)), @redcarpet %></a>
        </div>
      </div>
        <% end %>
    </div>
        <% unless row_cp == @redcarpet_photos.in_groups_of(4).last  %>
            <div class="divider"></div>
        <% end %>
   <% end %>
    <div  class="more_box">
      <div  class="more">
        <span>more from</span>
        <a href="<%= url_for redcarpets_path %>" class="more_link arrow_append">&nbsp;RED CARPET MOMENTS&nbsp;<span class="arrow_r_after"></span></a>
      </div>
    </div>
  </div>
</section>
 <% end end %>
</section>

app/views/home/search.html.erb
<section   class="span8">
  <% if @blogs.any? %>
  <header   class="header_title">
    <h1>BLOG</h1>
  </header>
  <div class="divider"></div>
  <section  id="events" class="events ">
    <div    class="cover_container ">
      <%= render @blogs %>
    </div>

  </section>
  <% end %>
  <% if @fashion_juries.any? %>
  <section  id="fashion_jury">
    <header class="header_title">
      <h1>FASHION JURY</h1>
    </header>
    <div class="row-fluid  jury_polaroid" id="fashion_juries">

      <%= render :partial => "fashion/fashion_juries/fashion_jury", :collection => @fashion_juries %>
    </div>
    <div class="clearfix"></div>
  </section>
  <% end %>
  <div class="clearfix"></div>
  <% if @trend_spottings.any? %>
<div style="margin-top: 10px;">
  <header   class="header_title">
    <h1>TREND SPOTTING</h1>
  </header>
  <div class="divider"></div>
  <section class="events">
    <div id="trend_spotting" class="row-fluid">
      <%= render :partial => "trend_spottings/trend_spotting", :collection => @trend_spottings %>
    </div>
  </section>
</div>
  <% end %>
  <% if @blogs.empty? && @trend_spottings.empty? && @fashion_juries.empty? %>
  <p class="alert alert-info">
    Sorry! no result matches your search
  </p>
  <% end %>
</section>