config/routes.rb
Cf::Application.routes.draw do

  resources :newsletters do
    member do
      post :mail_subscribers
    end
  end

  get 'tags/:tag', to: "blogs#index", as: :tag
  mount Ckeditor::Engine => '/ckeditor'

  resources :tips

  match "/search" => "home#search", :as => :search
  resources :magazines

  resources :videos

  resources :slides

  resources :right_ads

  resources :top_ads

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout" }, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :look_books do
    resources :photos
  end

  resources :functional_fashion_designers

  namespace :fashion do
    resources :fashion_juries
    resources :trend_spottings do
      resources :photos
    end
    resources :men_fashions  do
      resources :photos
    end
  end

  resources :trend_spottings do
    resources :photos
  end

  match '/fashion' => "fashion#show", :as => :fashion

  resource :runway

  namespace :runway do
    resources :collections do
      resources :photos
    end
    resources :seasons
    resources :years
  end

  namespace :style do
    resources :functional_fashions
    resources :look_books
    resources :tips
  end

  resources :redcarpets do
    resources :photos
  end

  resources :functional_fashions
  resources :blogs

  resources :features

  resources :photos
  resources :men_fashions do
    resources :photos
  end

  resources :fashion_juries

  resources :subscriptions

  match '/style' => "style#show", :as => :styles
  root :to => "home#index"

end

app/models/trend_spotting.rb
class TrendSpotting < ActiveRecord::Base
  attr_accessible :description, :title, :trend_cover, :caption, :published_at
  has_many :photos, :as => :photoable
  has_attached_file :trend_cover, :styles => {:trend_small => "200x350>", :original => "800x800>"}
  validates_attachment_presence :trend_cover
  validates_attachment_content_type :trend_cover, :content_type => ['image/jpeg', 'image/png', 'image/gif']
  validates_attachment_presence :trend_cover
  validates :title, :description, :trend_cover, :caption, :published_at, :presence => true
  scope :published, lambda { where('published_at <= ?', Time.now.utc) }
  scope :unpublished, lambda { where('published_at > ?', Time.now.utc) }
  scope :recent, order('published_at DESC')

  def to_param
    "#{id} #{title}".parameterize
  end

  def previous
    self.class.where("id < ?", id).order("id desc").first
  end

  def next
    self.class.where("id > ?", id).order("id").first
  end

  def published?
    published_at <= Time.zone.now
  end
  def last_published?
    self == self.class.published.last
  end
end

app/controllers/fashion/trend_spottings_controller.rb
class Fashion::TrendSpottingsController < ApplicationController
  load_and_authorize_resource
  def index
    @trend_spottings = TrendSpotting.accessible_by(current_ability).recent.includes(:photos).page(params[:page]).per_page(27)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trend_spottings }
    end
  end

  # GET /trend_spottings/1
  # GET /trend_spottings/1.json
  def show
    @trend_spotting = TrendSpotting.find(params[:id])
    @photos = @trend_spotting.photos

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trend_spotting }
    end
  end

  # GET /trend_spottings/new
  # GET /trend_spottings/new.json
  def new
    @trend_spotting = TrendSpotting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trend_spotting }
    end
  end

  # GET /trend_spottings/1/edit
  def edit
    @trend_spotting = TrendSpotting.find(params[:id])
  end

  # POST /trend_spottings
  # POST /trend_spottings.json
  def create
    @trend_spotting = TrendSpotting.new(params[:trend_spotting])

    respond_to do |format|
      if @trend_spotting.save
        format.html { redirect_to @trend_spotting, notice: 'Trend spotting was successfully created.' }
        format.json { render json: @trend_spotting, status: :created, location: @trend_spotting }
      else
        format.html { render action: "new", layout: "forms" }
        format.json { render json: @trend_spotting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trend_spottings/1
  # PUT /trend_spottings/1.json
  def update
    @trend_spotting = TrendSpotting.find(params[:id])

    respond_to do |format|
      if @trend_spotting.update_attributes(params[:trend_spotting])
        format.html { redirect_to @trend_spotting, notice: 'Trend spotting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit", layout: "forms" }
        format.json { render json: @trend_spotting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trend_spottings/1
  # DELETE /trend_spottings/1.json
  def destroy
    @trend_spotting = TrendSpotting.find(params[:id])
    @trend_spotting.destroy

    respond_to do |format|
      format.html { redirect_to trend_spottings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/trend_spottings_controller.rb
class TrendSpottingsController < ApplicationController
  load_and_authorize_resource
  def index
    @trend_spottings = TrendSpotting.accessible_by(current_ability).recent.includes(:photos).page(params[:page]).per_page(27)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trend_spottings }
    end
  end

  # GET /trend_spottings/1
  # GET /trend_spottings/1.json
  def show
    @trend_spotting = TrendSpotting.find(params[:id])
    @photos = @trend_spotting.photos

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trend_spotting }
    end
  end

  # GET /trend_spottings/new
  # GET /trend_spottings/new.json
  def new
    @trend_spotting = TrendSpotting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trend_spotting }
    end
  end

  # GET /trend_spottings/1/edit
  def edit
    @trend_spotting = TrendSpotting.find(params[:id])
  end

  # POST /trend_spottings
  # POST /trend_spottings.json
  def create
    @trend_spotting = TrendSpotting.new(params[:trend_spotting])

    respond_to do |format|
      if @trend_spotting.save
        format.html { redirect_to @trend_spotting, notice: 'Trend spotting was successfully created.' }
        format.json { render json: @trend_spotting, status: :created, location: @trend_spotting }
      else
        format.html { render action: "new", layout: "forms" }
        format.json { render json: @trend_spotting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trend_spottings/1
  # PUT /trend_spottings/1.json
  def update
    @trend_spotting = TrendSpotting.find(params[:id])

    respond_to do |format|
      if @trend_spotting.update_attributes(params[:trend_spotting])
        format.html { redirect_to @trend_spotting, notice: 'Trend spotting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit", layout: "forms" }
        format.json { render json: @trend_spotting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trend_spottings/1
  # DELETE /trend_spottings/1.json
  def destroy
    @trend_spotting = TrendSpotting.find(params[:id])
    @trend_spotting.destroy

    respond_to do |format|
      format.html { redirect_to trend_spottings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trend_spottings_helper.rb
module TrendSpottingsHelper
end

app/views/trend_spottings/_form.html.erb
<%= simple_form_for(@trend_spotting, html: {class: "form-horizontal"}) do |f| %>


   <%= f.input :title %>
   <%= f.input :description, input_html: {rows: 7, style: "width: 707px;"} %>
    <%= f.input :trend_cover, as: :file, label: "Upload cover image" %>

  <%= f.input :caption, label: "About image"%>
    <%= f.input :published_at, as: :string %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn" %>
  </div>


<% end %>

app/views/trend_spottings/_index_view_point.html.erb
<%= provide :title, "Trend Spotting" %>
<section   class="span8">
  <header   class="header_title">
    <h1><a>TREND SPOTTING</a></h1>
  </header>
  <div class="divider"></div>
  <section  id="events" class="events">
    <div id="trend_spotting" class="row-fluid">
      <%= render :partial => "trend_spottings/trend_spotting", :collection => trend_spottings %>
    </div>
  <% if  trend_spottings.next_page || trend_spottings.previous_page %>
    <div class="pager" style="margin-top: 30px;">
      <%= will_paginate trend_spottings %>
    </div>
  <% end %>

  </section>
</section>

<%= content_for :javascript do %>
    <script type="text/javascript">
        var $trendSpotting = $('#trend_spotting');
        $trendSpotting.imagesLoaded(function(){
            $trendSpotting.masonry({
                itemSelector : '.trending_items',
                columnWidth : function( containerWidth ) {
                    return containerWidth / 3;
                }
            });
        });
    </script>
<% end %>

app/views/trend_spottings/_photos.html.erb
<div class="mcol2    box">
  <%= image_tag photo.photo(:trend_small), :alt => "" %>
</div>

app/views/trend_spottings/_show_point.html.erb
<%= provide :title, @trend_spotting.title %>
  <div    id="main_section"   class="span8 ">
    <section  id="show_page" class="trend_show">
      <header   class="show_header">
        <h1 class="">
          <a href="#">
            <%= @trend_spotting.title %>
          </a>
        </h1>
      </header>
      <p class="blog_meta">posted in
        <a  class="transitionable category" href="<%= url_for fashion_trend_spottings_path %>">
          <span>TREND SPOTTING</span>
        </a>
        <span class="date"> on&nbsp;&nbsp;<%= trend_spotting.published_at.strftime("%^b  %d  %I:%M%p")%></span>
      </p>
      <div id="blocks"    class="">
        <div class="mcol3 desc box">
          <p><%= trend_spotting.description %></p>
        </div>
    <% @trend_spotting.photos.each do |photo| %>
        <div class="mcol2 box">
          <%= image_tag photo.photo(:trend_small) %>
        </div>
    <% end %>
      </div>
      <%= render "next_page", :obj => trend_spotting %>
      <% if can? :manage, TrendSpotting %>
          <div class="form-actions">
            <%= link_to "Manage Photos", fashion_trend_spotting_photos_path(trend_spotting), class: "btn" %>
            <%= link_to "Edit", edit_trend_spotting_path(trend_spotting), class: 'btn' %>
            <%= link_to "Delete", trend_spotting, method: :delete, data:{confirm: "Are you sure?"}, class: "btn btn-danger" %>
          </div>
      <% end %>
    </section>
  </div>

<%= content_for :javascript do %>
    <script type="text/javascript">
        var $container =  $('#blocks');
        $container.imagesLoaded(function(){
            $container.masonry({
                itemSelector: '.box',
                columnWidth: 100
            });
        });

    </script>
<% end %>

app/views/trend_spottings/_trend_spotting.html.erb
<%
  #locals
  @photos = trend_spotting.photos.limit(2)
%>
<div id="trend_spotting" class="row-fluid transitionable">
  <div class="trending_items span4">
    <div class="row-fluid">
      <div class="trend_box">
        <header class="">
          <h1 class="">
            <%= link_to  fashion_trend_spotting_path(trend_spotting), :rel => "tooltip", title: trend_spotting.title, class: "arrow_append" do %>
                <%= trend_spotting.title %>
                <span class="arrow_r_after"></span>
            <% end %>
          </h1>
        </header>
        <div class="item_grid ">
          <ul  class="items row-fluid">
            <% @photos.each do |photo| %>
            <li	class="item span12">
              <div  class="thumbnail tip_it_down" rel="tooltip" title="<%= photo.caption %>">
                <%= image_tag photo.photo(:trend_small), :alt => "" %>
              </div>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>


</div>

app/views/trend_spottings/edit.html.erb
<section   class="span12">
  <div class="page-header">
    <h1>Editing trend spotting</h1>
  </div>


  <%= render 'form' %>

  <%= link_to 'Back', trend_spottings_path %>
</section>

app/views/trend_spottings/index.html.erb
<%= render "trend_spottings/index_view_point",  trend_spottings: @trend_spottings%>

app/views/trend_spottings/new.html.erb
<section   class="span8">
  <div class="page-header">
    <h1>New trend spotting</h1>
  </div>


  <%= render 'form' %>

  <%= link_to 'Back', trend_spottings_path %>
</section>

app/views/trend_spottings/show.html.erb
<%= render "trend_spottings/show_point", trend_spotting: @trend_spotting%>